- name: variables from PLAY level
  hosts: web
  vars: 
    Course: "Devops"
    Trainer: "Sivakumar"
    Duration: "120 HRS"
  tasks: 
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}}, Trainer is {{Trainer}}, Duration is{{Duration}}"