- name: variables
  hosts: web
  vars:
    Name: "lucky"
    wishes: "gudmng"
  tasks: 
  - name: checking
    vars:
    wishes: "gud nite"
    ansible.builtin.debug:
      msg: "iam name is  {{Name}}, wishes is {{wishes}}"
