- name: loops
  hosts: localhost
  become: yes
  tasks: 
  - name: print persons
    ansible.builtin.user:
      name: "{{item}}"
      state: present
      group: wheel
    loop:
    - lucky
    - nani
      
      