- name: create users
  hosts: web
  become: yes
  tasks: 
  - name: checking user
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
      git
      mysql
      
      